### PR TITLE
Update to stable versions of Livewire, Folio and Volt.

### PR DESCRIPTION
**Pull request by mdavis1982**
This PR updates Genesis to use the stable versions of Livewire, Folio and Volt.

### CODE REVIEW

**Comment by mdavis1982** [comment]
I think this will also require releasing a stable version of Genesis as well.

**Comment by tnylea** [comment]
You sir 👇 You rock 🤘

Thank you. I'll get this merged in and tag a new release tomorrow. Super appreciate it.

Feel free to send me over any other feedback that you think would be good to add to this starter kit. I've already got 2FA and Teams (similar to jetstream), but let me know what your thoughts 😉

**Comment by mdavis1982** [comment]
I'd actually really like to make Folio optional (which I don't think would be too difficult).

I love this starter kit but I find Folio difficult to work with because I want to see all my routes in one place. 

If you're interested then I'm sure I could PR a version that has an install command that asks if you want to use it 😄

**Comment by tnylea** [comment]
Thanks @mdavis1982, actually the reason for creating this starter kit was to re-create the Laravel starter kits and making them use Folio and Volt. So, making Folio optional would kind of go against that. Let me know if you see it another way, I'm totally open to suggestions 😉

Getting this merged in now 👍

**Pull request merged**
